# Chameleon Vitae - golangci-lint v2 configuration
# https://golangci-lint.run/docs/configuration/file/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - unused
    - bodyclose
    - errorlint
    - makezero
    - nilerr
    - noctx
    - revive

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - io.Copy
        - io.ReadAll
        - (*encoding/json.Encoder).Encode
        - (*net/http.ResponseWriter).Write
        - (net/http.ResponseWriter).Write
        - (github.com/jackc/pgx/v5.Tx).Rollback
        - (*github.com/jackc/pgx/v5.Tx).Rollback
        - (pgx.Tx).Rollback

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    gosec:
      excludes:
        - G115  # Integer overflow conversion - handled by business logic
        - G301  # Directory permissions - acceptable for local storage
        - G304  # File path from variable - handled by sanitization
        - G104  # Unhandled errors in tests

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: superfluous-else

  exclusions:
    presets:
      - comments
      - std-error-handling

    paths:
      - vendor
      - frontend

    rules:
      # Ignore unused-parameter in mocks and test files
      - linters: [revive]
        path: "_test\\.go$"
        text: "unused-parameter"
      - linters: [revive]
        path: "mocks/"
        text: "unused-parameter"
      # Ignore errcheck in test files
      - linters: [errcheck]
        path: "_test\\.go$"
      # Ignore noctx in test files
      - linters: [noctx]
        path: "_test\\.go$"
      # Ignore package naming for http adapter
      - linters: [revive]
        path: "adapters/primary/http/"
        text: "var-naming: avoid package names"
      # Ignore empty-block for intentional empty error handlers
      - linters: [revive]
        text: "empty-block"
      # Ignore deprecated Firebase options (no alternative available)
      - linters: [staticcheck]
        text: "SA1019.*option\\.With"
      # Ignore QF1008 for embedded field selectors (clarity over brevity)
      - linters: [staticcheck]
        text: "QF1008"
      # Ignore unused in test utility files
      - linters: [unused]
        path: "_test\\.go$"
      # Ignore SA9003 empty branch (intentional no-op error handling)
      - linters: [staticcheck]
        text: "SA9003"
      # Ignore DomainError stuttering (established domain pattern)
      - linters: [revive]
        text: "stutters"
        path: "domain/errors\\.go$"
      # Ignore errorlint for wrapped error patterns in config
      - linters: [errorlint]
        path: "config/config\\.go$"
        text: "type assertion on error"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
